import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/organisms/Header";
import Navbar from "@/components/organisms/Navbar";
import Footer from "@/components/organisms/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="layout">
          <Header></Header>
          <div>
          <Navbar></Navbar>
            {children}
          </div>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
